### ISSUE TITLE
Can't add img to review

### ISSUE THREAD

**Issue by M-Klimov** [M-Klimov/st-extension#15]
После открытия окна с выбором изображения к отзыву расширение закрывается.

**Comment by M-Klimov** [comment]
В настройках такая же проблема с изображением

**Comment by pashog** [comment]
Какая ОС, версия браузера?

**Comment by M-Klimov** [comment]
Ubuntu 16.04, Chromium Version 76.0.3809.100 (Official Build) snap (64-bit). Сейчас попробую в хроме, может отличаются.

**Comment by M-Klimov** [comment]
В Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit) тоже не работает

**Comment by pashog** [comment]
29469e078d36ac04fa1f60f8b258d6a96675eed5 
![image](https://user-images.githubusercontent.com/1691041/63911844-6a2db000-ca34-11e9-92de-83cfdfd42b3b.png)
